<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>NIN Enrollment Verification Portal</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 flex flex-col items-center justify-center min-h-screen">

  <div class="bg-white shadow-xl rounded-2xl p-8 w-96">
    <h1 class="text-2xl font-bold text-center text-blue-700 mb-6">NIN Enrollment Verification</h1>

    <input id="ninInput" type="text" placeholder="Enter Tracking ID" class="w-full border border-gray-300 rounded-lg p-3 mb-4" />

    <button onclick="verifyNIN()" class="bg-blue-600 text-white w-full py-2 rounded-lg hover:bg-blue-700">
      Verify
    </button>

    <div id="result" class="mt-6 text-center"></div>
  </div>

  <script>
    // Dummy data (replace this with live data or connect to your backend)
    const database = {
      "12345678901": { name: "Musa Ahmed", status: "Successful", date: "2025-09-10", center: "Abuja HQ" },
      "23456789012": { name: "Grace Okon", status: "Pending", date: "2025-10-01", center: "Lagos Center" },
      "34567890123": { name: "Amina Bello", status: "Failed", date: "2025-09-29", center: "Kaduna Center" }
    };

    function verifyNIN() {
      const input = document.getElementById('ninInput').value.trim();
      const resultBox = document.getElementById('result');
      const record = database[input];

      if (record) {
        resultBox.innerHTML = `
          <div class="p-4 border rounded-lg bg-green-50">
            <p><strong>Name:</strong> ${record.name}</p>
            <p><strong>Status:</strong> ${record.status}</p>
            <p><strong>Date Enrolled:</strong> ${record.date}</p>
            <p><strong>Center:</strong> ${record.center}</p>
          </div>`;
      } else {
        resultBox.innerHTML = `<p class="text-red-600 font-semibold">No record found for Tracking ID: ${input}</p>`;
      }
    }
  </script>

</body>
</html>
